# Idris, Ivan. NumPy: Beginner's Guide. Packt Publishing Ltd, 2015.

### NumPy 数组对象

In [6]:
import numpy as np

In [9]:
a = np.array([0, 1, 2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [11]:
a.shape

(5,)

In [14]:
m = np.array([np.arange(2), np.arange(2)]) 

In [15]:
m.shape

(2, 2)

In [17]:
np.arange(7, dtype='f')

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [18]:
# “整数	i
# 无符号整数	u
# 单精度浮点	f
# 双精度浮点	d
# 布尔型	b
# 复数	D
# 字符串	S
# Unicode	U
# 无	V”

### 创建记录数据类型

In [23]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [24]:
t['name'] #查看类型

dtype('<U40')

### 切片和索引

In [26]:
a = np.arange(9)

In [27]:
a[3:7]

array([3, 4, 5, 6])

In [28]:
a[:7:2]

array([0, 2, 4, 6])

In [29]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
b[:,0,0]

array([ 0, 12])

In [35]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b[0,1]

array([4, 5, 6, 7])

In [39]:
b[0,1,::2]

array([4, 6])

In [40]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [41]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [42]:
b[0,:,1]

array([1, 5, 9])

In [45]:
b[0,:,-1]

array([ 3,  7, 11])

In [46]:
b[0,::1,-1]

array([ 3,  7, 11])

In [48]:
b[0,::2,-1]

array([ 3, 11])

In [49]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### 处理数组形状

In [50]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
b.shape=(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [58]:
b.resize(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])